version: "3.3"

services:
  spring-test-db:
    image: postgres:12.0
    container_name: spring-test-db
    env_file:
      - ./src/main/resources/.env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - "db-dev:/var/lib/postgresql/data"

  spring-test-pgadmin:
    image: dpage/pgadmin4:4.14
    container_name: spring-test-pgadmin
    env_file:
      - ./src/main/resources/.env
    ports:
      - "5431:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    networks:
      - backend
    depends_on:
      - spring-test-db

networks:
  backend:

volumes:
  pgadmin:
  db-dev: